/**
 * Module Name - AccIouSlip
 * Purpose - Entity of IOU Slip
 **/

package com.athena.mis.accounting.entity

class AccIouSlip {

    long id                         // primary key (Auto generated by its own sequence)
    int version
    long employeeId                 // Employee.id
    long projectId                  // Project.id
    long approvedBy                 // AppUser.id (Role Director Or Project Director)
    boolean sentForApproval         // true : mail sent to director/PD, false: mail not sent to director/PD

    long createdBy                  // AppUser.id
    Date createdOn                  // Object creation DateTime
    long updatedBy                  // AppUser.id
    Date updatedOn                  // Object Updated DateTime

    long companyId                  // Company.id
    long indentId                   // Indent.id
    double totalPurposeAmount       // total amount of its accIouPurpose amount
    int purposeCount                // number of its purposes

    static mapping = {
        id generator: 'sequence', params: [sequence: 'acc_iou_slip_id_seq']
        employeeId index: 'acc_iou_slip_employee_id_idx'
        projectId index: 'acc_iou_slip_project_id_idx'
        approvedBy index: 'acc_iou_slip_approved_by_idx'
        createdBy index: 'acc_iou_slip_created_by_idx'
        updatedBy index: 'acc_iou_slip_updated_by_idx'
        indentId index: 'acc_iou_slip_indent_by_idx'
        companyId index: 'acc_iou_slip_company_by_idx'

    }

    static constraints = {
        employeeId(nullable: false)
        projectId(nullable: false)
        approvedBy(nullable: false)
        sentForApproval(nullable: false)
        createdBy(nullable: false)
        createdOn(nullable: false)
        updatedBy(nullable: false)
        companyId(nullable: false)
        indentId(nullable: false)
        totalPurposeAmount(nullable: false)
        purposeCount(nullable: false)
        updatedOn(nullable: true)
    }


    static namedQueries = {
        getApprovedIouTotalByIndent { long indentId ->
            eq('indentId',indentId)
            gt('approvedBy',0L)
            projections{
                sum('totalPurposeAmount')
            }
        }
    }

}
