/**
 * Module  - Inventory
 * Purpose - Entity that contains all properties of Production Details
 */

package com.athena.mis.inventory.entity

class InvProductionDetails {
    long id                             // primary key (Auto generated by its own sequence)
    int version                         // Object version in persistence layer
    long productionLineItemId           // ProductionLineItem.id (e.g. Ready mix)
    long productionItemTypeId           // ProductionItemType.id  (e.g. Raw material)
    long materialId                     // Item.id
    long companyId                      // Company.id

    /*if  productionItemTypeId = SystemEntity.id (Finished Product)
            then set overHeadCost
      OtherWise for SystemEntity.id (Raw Material)
            set overHeadCost = 0d
     */
    double overheadCost

    static mapping = {
        id generator: 'sequence', params: [sequence: 'inv_production_details_id_seq']
        overheadCost sqlType: "numeric(16,4)"

        productionLineItemId index: 'inv_production_details_production_line_item_id_idx'
        productionItemTypeId index: 'inv_production_details_production_item_type_id_idx'
        materialId index: 'inv_production_details_material_id_idx'
        companyId index: 'inv_production_details_company_id_idx'
    }

    static constraints = {
        productionLineItemId(nullable: false)
        productionItemTypeId(nullable: false)
        materialId(nullable: false)
        overheadCost(nullable: false)
        companyId(nullable: false)
    }
}
