/**
 * Module Name - Fixed asset
 * Purpose - Entity of Fixed asset movement information
 * */

 package com.athena.mis.fixedasset.entity

class FxdFixedAssetTrace {

    long id                     // primary key (Auto generated by its own sequence)
    int version
    long fixedAssetDetailsId    // fixedAssetDetails.id
    long itemId                 // item.id (type = fixed asset)
    long inventoryId            // Inventory.id
    Date transactionDate        // date of fixed asset transaction
    boolean isCurrent           /* true = when current inventory is equal to its FADetails inventory
                                   false = when current inventory is not equal to its FADetails inventory
                                */
    String comments

    long createdBy              // AppUser.Id
    Date createdOn              // Object creation DateTime

    long companyId               // Company.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'fxd_fixed_asset_trace_id_seq']
        transactionDate type: 'date'

        fixedAssetDetailsId index: 'fixed_asset_trace_fixed_asset_details_id_idx'
        itemId index: 'fixed_asset_trace_item_id_idx'
        inventoryId index: 'fixed_asset_trace_inventory_id_idx'
        createdBy index: 'fixed_asset_trace_created_by_idx'
        companyId index: 'fixed_asset_trace_company_id_idx'
    }

    static constraints = {
        fixedAssetDetailsId(nullable: false)
        itemId(nullable: false)
        inventoryId(nullable: false)
        transactionDate(nullable: false)
        isCurrent(nullable: false)
        comments(nullable: true)
        createdBy(nullable: false)
        createdOn(nullable: false)
        companyId(nullable: false)
    }
}
