/**
 * Module Name - Accounting
 * Purpose - Entity of accounting custom group name
 **/

package com.athena.mis.accounting.entity

class AccCustomGroup {
    long id                     // primary key (Auto generated by its own sequence)
    int version
    String name                // Unique Custom Group Name
    String description
    boolean isActive           // flag to consider/ignore the object
    long companyId             // Company.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'acc_custom_group_id_seq']
        companyId index: 'acc_custom_group_company_id_idx'
    }

    static constraints = {
        name(nullable: false)
        description(nullable: true)
        isActive(nullable: false)
        companyId(nullable: false)
    }
}
