/**
 * Module Name - Accounting
 * Purpose - Entity of accounting division name
 **/

package com.athena.mis.accounting.entity

class AccDivision {
    long id                // primary key (Auto generated by its own sequence)
    int version
    String name            // Unique name of Division
    long projectId         // foreign key of Project
    boolean isActive       // flag to consider/ignore the object

    long createdBy         // AppUser.id
    Date createdOn         // Object creation DateTime
    long updatedBy = 0     // AppUser.id
    Date updatedOn         // Object Updated DateTime
    long companyId         // Company.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'acc_division_id_seq']
        projectId index: 'acc_division_project_id_idx'
        createdBy index: 'acc_division_created_by_idx'
        updatedBy index: 'acc_division_updated_by_idx'
        companyId index: 'acc_division_company_id_idx'
    }

    static constraints = {
        name(nullable: false)
        projectId(nullable: false)
        isActive(nullable: false)
        updatedOn(nullable: true)
        companyId(nullable: false)
    }
}
