/**
 * Module Name - Accounting
 * Purpose - Entity of accounting group
 **/

package com.athena.mis.accounting.entity

class AccGroup {
    long id                 // primary key (Auto generated by its own sequence)
    int version
    String name             //Name of group
    String description
    boolean isActive        // flag to consider/ignore the object
    long companyId          // Company.id
    boolean isReserved      // Reserved Group can not be updated or deleted
    String systemAccGroup   // reserved acc group name string

    static mapping = {
        id generator: 'sequence', params: [sequence: 'acc_group_id_seq']
        companyId index: 'acc_group_company_id_idx'
    }

    static constraints = {
        description(nullable: true)
        companyId(nullable: false)
        isReserved(nullable: false)
        systemAccGroup(nullable: false)
        systemAccGroup unique: 'companyId'

    }

    public String toString() {
        return this.name
    }
}
