/**
 * Module Name - Accounting
 * Purpose - Entity of accounting sub account
 **/

package com.athena.mis.accounting.entity

class AccSubAccount {

    int id                      // primary key (Auto generated by its own sequence)
    int version
    long coaId                  // AccChartOfAccount.id
    String description
    boolean isActive = false    // flag to consider/ignore the object

    long createdBy              // AppUser.id
    Date createdOn              // Object creation DateTime
    long updatedBy = 0          // AppUser.id
    Date updatedOn              // Object Updated DateTime
    long companyId              // Company.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'acc_sub_account_id_seq']

        coaId index: 'acc_sub_account_coa_id_idx'
        createdBy index: 'acc_sub_account_created_by_idx'
        updatedBy index: 'acc_sub_account_updated_by_idx'
        companyId index: 'acc_sub_account_company_id_idx'
    }

    static constraints = {
        updatedOn(nullable: true)
        companyId(nullable: false)
    }
}


