/**
 * Module Name - Accounting
 * Purpose - Entity of accounting tire3 name
 **/

package com.athena.mis.accounting.entity

class AccTier3 {
    int id                          // primary key (Auto generated by its own sequence)
    int version
    String name                     // Unique name
    long accTypeId                   // AccType.id
    int accTier1Id                  // AccTire1.id
    int accTier2Id                  // AccTire2.id
    boolean isActive = false        // flag to consider/ignore the object
    long companyId                  // Company.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'acc_tier3_id_seq']
        accTier2Id index: 'acc_tier3_acc_tier2id_id_idx'
        accTier1Id index: 'acc_tier3_acc_tier1id_idx'
        accTypeId index: 'acc_tier3_acc_type_id_idx'
        companyId index: 'acc_tier3_company_id_idx'
    }

    public String toString() {
        return this.name
    }

    static constraints = {
        companyId(nullable: false)
    }
}
