/**
 * Module Name - Budget
 * Purpose - Entity of Budget details information
 * */
package com.athena.mis.budget.entity

class BudgBudgetDetails {
    long id                     // primary key (Auto generated by its own sequence)
    int version
    long budgetId               // BudgBudget.id (Parent id)
    long projectId              // Project.id (Redundant)
    long itemId                 // Item.id
    double quantity             // Quantity of this item
    double totalConsumption     // total consumption of this item
    Date createdOn              // Object creation DateTime
    long createdBy              // AppUser.id
    Date updatedOn              // Object updated DateTime
    long updatedBy              // AppUser.id
    String comments
    double rate                 // Rate of this item
    long companyId              // Company.id
    boolean isConsumedAgainstFixedAsset = false // is this item consumed against Fixed Asset
    boolean isUpToDate          // for procurement budget (if item is up to date according to schema then true, otherwise false)

    static mapping = {
        id generator: 'sequence', params: [sequence: 'budg_budget_details_id_seq']
        quantity sqlType: "numeric(16,4)"
        totalConsumption sqlType: "numeric(16,4)"
        rate sqlType: "numeric(16,4)"

        budgetId index: 'budget_details_budget_id_idx'
        projectId index: 'budget_details_project_id_idx'
        createdBy index: 'budget_details_created_by_idx'
        updatedBy index: 'budget_details_updated_by_idx'
        itemId index: 'budget_details_item_id_idx'
        companyId index: 'budget_details_company_id_idx'
    }

    static constraints = {
        createdOn(nullable: false)
        updatedOn(nullable: true)
        comments(nullable: true)
        itemId(nullable: false)
        totalConsumption(nullable: false)
        isConsumedAgainstFixedAsset(nullable: false)
    }
}
