package com.athena.mis.budget.entity

class BudgSprintBudget {
    long id                     // primary key (Auto generated by its own sequence)
    int version
    long sprintId               // BudgSprint.id
    long budgetId               // BudgBudget.id
    double quantity             // quantity
    Date createdOn              // Object creation DateTime
    long createdBy              // AppUser.id
    Date updatedOn              // Object updated DateTime
    long updatedBy              // AppUser.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'budg_sprint_budget_id_seq']

        quantity sqlType: "numeric(16,4)"
        sprintId index: 'sprint_budget_sprint_id_idx'
        budgetId index: 'sprint_budget_budget_id_idx'

    }

    static constraints = {
        quantity(nullable: false)
        sprintId(nullable: false)
        budgetId(nullable: false)
        createdOn(nullable: false)
        updatedOn(nullable: true)
    }
}
