/**
 * Module  - Budget
 * Purpose - Entity that contains all properties of BudgSprint
 */

package com.athena.mis.budget.entity

class BudgSprint {
    long id             // primary key (Auto generated by its own sequence)
    int version
    long projectId      // Project.id
    String name         // name of sprint e.g. LDCH 01-JAN-2014 To 31-DEC-2014 (LDCH --> project code)
    Date startDate      // start date of sprint
    Date endDate        // end date of sprint
    long createdBy      // AppUser.id
    Date createdOn      // Object creation DateTime
    long updatedBy      // AppUser.id
    Date updatedOn      // Object updated DateTime
    long companyId      // Company.id
    boolean isActive    // boolean value (true/false), if active then true otherwise false

    static mapping = {
        id generator: 'sequence', params: [sequence: 'budg_sprint_id_seq']

        projectId index: 'budg_sprint_project_id_idx'
        createdBy index: 'budg_sprint_created_by_idx'
        updatedBy index: 'budg_sprint_updated_by_idx'
        companyId index: 'budg_sprint_company_id_idx'
    }

    static constraints = {
        projectId(nullable: false)
        name(nullable: false)
        startDate(nullable: false)
        endDate(nullable: false)
        createdBy(nullable: false)
        createdOn(nullable: false)
        updatedBy(nullable: false)
        updatedOn(nullable: true)
        companyId(nullable: false)
        isActive(nullable: false)
    }
}
