/**
 * Module  - Budget
 * Purpose - Entity that contains all properties of BudgSchema
 */

package com.athena.mis.budget.entity

class BudgSchema {
    long id                     // primary key (Auto generated by its own sequence)
    int version
    long budgetId               // BudgBudget.id (Parent id)
    long projectId              // Project.id (redundant)
    long itemId                 // Item.id
    long itemTypeId             // ItemType.id
    double quantity              //Quantity of this item
    Date createdOn              // Object creation DateTime
    long createdBy              // AppUser.id
    Date updatedOn              // Object updated DateTime
    long updatedBy              // AppUser.id
    String comments             // comments
    double rate                 // Rate of this item
    long companyId              // Company.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'budg_schema_id_seq']
        quantity sqlType: "numeric(16,4)"
        rate sqlType: "numeric(16,4)"

        budgetId index: 'budg_schema_budget_id_idx'
        projectId index: 'budg_schema_project_id_idx'
        createdBy index: 'budg_schema_created_by_idx'
        updatedBy index: 'budg_schema_updated_by_idx'
        itemId index: 'budg_schema_item_id_idx'
        itemTypeId index: 'budg_schema_item_type_id_idx'
        companyId index: 'budg_schema_company_id_idx'
    }

    static constraints = {
        createdOn(nullable: false)
        updatedOn(nullable: true)
        comments(nullable: true)
        itemId(nullable: false)
        budgetId(nullable: false)
        projectId(nullable: false)
        itemTypeId(nullable: false)
    }
}
