package com.athena.mis.budget.entity

class BudgTask {
    long id                     // primary key (Auto generated by its own sequence)
    int version
    String name                 // budget task unique name
    Date startDate              // start date of task
    Date endDate                // end date of task
    long statusId               // SystemEntity.id
    long budgetId               // BudgBudget.id (Parent id)
    long companyId              // Company.id

    Date createdOn              // Object creation DateTime
    long createdBy              // AppUser.id
    Date updatedOn              // Object updated DateTime
    long updatedBy              // AppUser.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'budg_task_id_seq']
        startDate type: 'date'
        endDate type: 'date'

        //indexing
        statusId index: 'budg_task_status_id_idx'
        companyId index: 'budg_task_company_id_idx'
        createdBy index: 'budg_task_created_by_idx'
        updatedBy index: 'budg_task_updated_by_idx'
    }

    static constraints = {
        name(nullable: false)
        statusId(nullable: false)
        startDate(nullable: false)
        endDate(nullable: false)
        companyId(nullable: false)
        createdOn(nullable: false)
        updatedOn (nullable: true)
    }
}
