/**
 * Module Name - Accounting
 * Purpose - Entity of accounting voucher details information
 **/

package com.athena.mis.accounting.entity

class AccVoucherDetails {
    long id                 // primary key (Auto generated by its own sequence)
    int version

    long projectId          // Project.id    (optional)
    long voucherId          // AccVoucher.id(Parent Id)
    int rowId               // determine hierarchy of VoucherDetails for same voucher (First Debit then Credit)
    long coaId              // AccChartOfAccount.id
    long groupId            // AccGroup.id
    long sourceId           // AccSource.id
    long sourceTypeId       // SystemEntity.id eg: None,employee,supplier etc.
    long sourceCategoryId   // e.g. Item.itemTypeId, Employee.designationId etc
    long divisionId         // AccDivision.id
    double amountDr         // Amount debited
    double amountCr         // Amount credited
    String particulars      // Optional

    long createdBy          // AppUser.id
    Date createdOn          // Object creation DateTime

    static mapping = {
        id generator: 'sequence', params: [sequence: 'acc_voucher_details_id_seq']
        amountDr sqlType: "numeric(16,4)"
        amountCr sqlType: "numeric(16,4)"

        coaId index: 'acc_voucher_details_coa_id_idx'
        projectId index: 'acc_voucher_details_project_id_idx'
        voucherId index: 'acc_voucher_details_voucher_id_idx'
        groupId index: 'acc_voucher_details_group_id_idx'
        sourceId index: 'acc_voucher_details_source_id_idx'
        sourceTypeId index: 'acc_voucher_details_source_type_id_idx'
        sourceCategoryId index: 'acc_voucher_details_source_category_id_idx'
        divisionId index: 'acc_voucher_details_division_id_idx'
        createdBy index: 'acc_voucher_details_created_by_idx'
    }
    static constraints = {
        particulars(nullable: true)
    }
}
