/**
 * Module Name - Application
 * Purpose - Entity of project information
 **/

package com.athena.mis.application.entity

class Project {
    long id               // primary key (Auto generated by its own sequence)
    int version
    String code           // Project Code
    String name           // Unique project name
    String description    //Project description
    Date createdOn       // Object creation DateTime
    long createdBy       // AppUser.id
    Date updatedOn       // Object updated DateTime
    long updatedBy       // AppUser.id
    long companyId       // Company.id
    int contentCount     // total number of content
    Date startDate                          // start date
    Date endDate                            // end date

    // these flags determine auto-approval for transaction(In(Supplier/Inventory)/Out/Production/Consumption)
    boolean isApproveInFromSupplier = false
    boolean isApproveInFromInventory = false
    boolean isApproveInvOut = false
    boolean isApproveConsumption = false
    boolean isApproveProduction = false

    static mapping = {
        id generator: 'sequence', params: [sequence: 'project_id_seq']

        createdBy index: 'project_created_by_idx'
        updatedBy index: 'project_updated_by_idx'
        companyId index: 'project_company_id_idx'
    }

    static constraints = {
        code(nullable: false)
        name(nullable: false)
        contentCount(nullable: false)
        description(nullable: true)
        createdOn(nullable: false)
        createdBy(nullable: false)
        updatedOn(nullable: true)
        updatedBy(nullable: false)
        companyId(nullable: false)
        isApproveInFromSupplier(nullable: false)
        isApproveInFromInventory(nullable: false)
        isApproveInvOut(nullable: false)
        isApproveConsumption(nullable: false)
        isApproveProduction(nullable: false)
        startDate(nulable: false)
        endDate(nulable: false)
    }
}
