package com.athena.mis.arms.entity

/**
 * Module  - ARMS
 * Purpose - Entity that contains all properties of RmsExchangeHouse
 */
class RmsExchangeHouse {

    long id                 // primary key (Auto generated by its own sequence)
    int version             // object version persisted in DB
    String name             // Name of RmsExchangeHouse
    String code             // Code of RmsExchangeHouse
    long countryId          // Country.id
    long companyId          // Company.id
    double balance

    static mapping = {
        id generator: 'sequence', params: [sequence: 'rms_exchange_house_id_seq']
        countryId index: 'rms_exchange_house_country_id_idx'
        companyId index: 'rms_exchange_house_company_id_idx'
        balance sqlType: 'numeric(16,2)'
    }

    static constraints = {
        name unique: true
        code unique: true
        balance(nullable:true)
    }
}
