package com.athena.mis.application.entity

/**
  RoleType entity is used to determine the different type of role(s)
 * */

 class RoleType {
    long id             // primary key (Auto generated by its own sequence)
    String name         // Role Name e.g: Director, Project Manager etc.
    String authority    // Role short name format(ROLE_Role.id) e.g ROLE_-1, ROLE_5

    static mapping = {
        version false
    }

    static constraints = {
        name(nullable: false)
        authority(nullable: false)
    }
}
