/**
 * Module Name - Fixed asset
 * Purpose - Entity of Fixed asset maintenance information
 * */

 package com.athena.mis.fixedasset.entity

class FxdMaintenance {

    long id                  // primary key (Auto generated by its own sequence)
    int version
    long itemId              //Item.id
    long fixedAssetDetailsId //FixedAssetDetails.Id
    long maintenanceTypeId   //MaintenanceType.Id
    double amount            //Maintenance Cost
    Date maintenanceDate     //Maintenance Date
    String description       //Maintenance description

    Date createdOn           // Object creation DateTime
    long createdBy           // Appuser.id
    Date updatedOn           // Object updated DateTime
    long updatedBy           // AppUser.id

    long companyId          // Company.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'fxd_maintenance_id_seq']
        maintenanceDate type: 'date'

        itemId index: 'fxd_maintenance_item_id_idx'
        fixedAssetDetailsId index: 'fxd_maintenance_fixed_asset_details_id_idx'
        maintenanceTypeId index: 'fxd_maintenance_maintenance_type_id_idx'
        createdBy index: 'fxd_maintenance_created_by_idx'
        updatedBy index: 'fxd_maintenance_updated_by_idx'
        companyId index: 'fxd_maintenance_company_id_idx'
    }

    static constraints = {
        itemId(nullable: false)
        fixedAssetDetailsId(nullable: false)
        maintenanceTypeId(nullable: false)
        amount(nullable: false)
        maintenanceDate(nullable: false)
        description(nullable: false)
        createdOn(nullable: false)
        createdBy(nullable: false)
        updatedOn(nullable: true)
        updatedBy(nullable: false)
        companyId(nullable: false)
    }
}