package com.athena.mis.projecttrack.entity

class PtFlow {

    long id				 // object.id (primary key - auto generated by own id_seq)
    int version          // object.version
    String flow          // flow
    long backlogId       // PtBacklog.id
    long companyId       // Company.id

    long createdBy       // AppUser.id
    Date createdOn
    long updatedBy = 0L  // AppUser.id
    Date updatedOn

    static constraints = {
        createdBy(nullable: false)
        createdOn(nullable: false)
        updatedOn(nullable: true)
    }

    static mapping = {
        id generator: 'sequence' , params: [sequence : 'pt_flow_id_seq']
        createdBy index: 'pt_flow_created_by_idx'
        backlogId index: 'pt_flow_backlog_id_idx'
        companyId index: 'pt_flow_company_id_idx'
    }
}
