package com.athena.mis.arms.entity

/**
 * Module  - ARMS
 * Purpose - Entity that contains all properties of RmsTaskTrace
 */

class RmsTaskTrace {

    long id                         // object.id auto generated by it's own sequence
    long taskId                     // RmsTask.id
    long previousStatus             // SystemEntity.id
    long currentStatus              // SystemEntity.id
    boolean isRevised               // RmsTask.isRevised
    Date createdOn = new Date()     // created on (always new Date())
    long createdBy                  // AppUser.id
    long companyId                  // Company.id

    static mapping = {
        version false
        id generator: 'sequence', params: [sequence: 'rms_task_trace_id_seq']
        taskId index: 'rms_task_trace_task_id_idx'
        companyId index: 'rms_task_trace_company_id_idx'
    }
}
