package com.athena.mis.document.entity

class DocDbInstance {

    long id                   //Primary Key (Auto Generated By it's own sequence)
    int version
    String instanceName       //Name of the DB
    long vendorId             //SystemEntity.id (Postgre, MySQL)
    String driver             //Driver of DB
    String connectionString   //Connection String of DB
    String sqlQuery           //Query for execute in DB
    long companyId            //Company.id
    Date createdOn            //Created Datetime
    long createdBy            //AppUser.id
    Date updatedOn            //Updated datetime
    long updatedBy            //AppUser.id


    static mapping = {
        id generator: 'sequence', params: [sequence: 'doc_db_instance_id_seq']
        vendorId index: 'doc_db_instance_vendor_id_idx'
        companyId index: 'doc_db_instance_company_id_idx'
        createdBy index: 'doc_db_instance_created_by_idx'
        updatedBy index: 'doc_db_instance_updated_by_idx'
    }

    static constraints = {
        instanceName(nullable: false)
        driver(nullable: false)
        vendorId(nullable: false)
        connectionString(nullable: false)
        sqlQuery(nullable: false, maxSize: 2000)
        companyId(nullable: false)
        createdOn(nullable: false)
        createdBy(nullable: false)
        updatedBy(nullable: false)
        updatedOn(nullable: true)
        instanceName unique: 'companyId'
    }
}
