/**
 * Module Name - Budget
 * Purpose - Entity of budget type name
 **/


package com.athena.mis.budget.entity

class BudgBudgetScope {
    long id                // primary key (Auto generated by its own sequence)
    int version
    String name            // unique by application implementation
    long companyId         // Company.Id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'budg_budget_scope_id_seq']
        companyId index: 'budg_budget_scope_company_id_idx'
    }

    static constraints = {
        name(nullable: false)
        companyId(nullable: false)
    }

    public String toString() {
        return this.name
    }
}
