/**
 * Module Name - Budget
 * Purpose - Entity of budget information
 * */

package com.athena.mis.budget.entity

class BudgBudget {
    long id                                 // primary key (Auto generated by its own sequence)
    int version
    long projectId                          // Project.id
    String budgetItem                       // unique by application implementation
    String details
    int budgetScopeId                       // BudgBudgetScope.id
    Date createdOn                          // Object creation DateTime
    long createdBy                          // AppUser.id
    Date updatedOn                          // Object updated DateTime
    long updatedBy                          // AppUser.id
    int status                              // currently not implemented, Set 0 as default
    double budgetQuantity                   // Total budget Quantity
    int unitId                              // SystemEntity.id (Meter, Kg etc)
    double contractRate = 0.0d              // Mendatory for billable budget
    int itemCount = 0                       // number of item per budget
    boolean billable = false                // billable or non-billable
    long companyId                          // Company.id
    int contentCount                        // number of content per budget
    int taskCount                           // number of task per budget
    Date startDate                          // start date
    Date endDate                            // end date
    boolean isProduction                    // boolean value (true/false)

    static mapping = {
        id generator: 'sequence', params: [sequence: 'budg_budget_id_seq']

        budgetQuantity sqlType: "numeric(16,4)"
        contractRate sqlType: "numeric(16,4)"

        projectId index: 'budget_project_id_idx'
        budgetScopeId index: 'budget_budget_scope_id_idx'
        createdBy index: 'budget_created_by_idx'
        updatedBy index: 'budget_updated_by_idx'
        budgetItem index: 'budget_budget_item_idx'
        unitId index: 'budget_unit_id_idx'
        companyId index: 'budget_company_id_idx'
    }

    static constraints = {
        budgetItem(nullable: false)
        details(nullable: false, size: 0..1000)
        createdOn(nullable: false)
        updatedOn(nullable: true)
        status(nullable: false)
        unitId(nullable: false)
        itemCount(nullable: false)
        contentCount(nullable: false)
        taskCount(nullable: false)
        billable(nullable: false)
        contractRate(nulable: false)
        startDate(nulable: false)
        endDate(nulable: false)
    }
}
