package com.athena.mis.accounting.entity

class AccBankStatement {
    long id                          // primary key (Auto generated by its own sequence)
    int version
    Date transactionDate
    String transactionType
    String companyRef
    String narrative
    String bankRef
    String transactionRef
    double debit
    double credit
    double balance
    long bankAccId               // COA Id and COA group must be bank
    long companyId                   // company.id
    String chequeNo             // get cheque no from company ref
    double amount               // debit or credit
    long createdBy
    Date createdOn

    static mapping = {
        id generator: 'sequence', params: [sequence: 'acc_bank_statement_id_seq']
        bankAccId index: 'acc_bank_statement_bank_acc_id_idx'
        companyId index: 'acc_bank_statement_company_id_idx'
        createdBy index: 'acc_bank_statement_created_by_idx'
    }

    static constraints = {
        transactionDate(nullable: false)
        transactionType(nullable: false)
        companyRef(nullable: true)
        narrative(nullable: true)
        bankRef(nullable: true)
        transactionRef(nullable: false)
        debit(nullable: false)
        credit(nullable: false)
        balance(nullable: false)
        bankAccId(nullable: false)
        companyId(nullable: false)
        chequeNo(nullable: true)
        amount(nullable:false)
        createdBy(nullable:false)
        createdOn(nullable:false)
    }
}
