/**
 * Module Name - Application
 * Purpose - Keep Supplier item Information
 * */

 package com.athena.mis.application.entity

class SupplierItem {

    long id              // primary key (Auto generated by its own sequence)
    int version
    long supplierId      // Supplier.id (Parent)
    long itemId          // Item.id
    long companyId
    long createdBy          // AppUser.id
    Date createdOn          // Object creation DateTime
    long updatedBy = 0L     // AppUser.id
    Date updatedOn          // Object Updated DateTime

    static mapping = {
        id generator: 'sequence', params: [sequence: 'supplier_item_id_seq']
        supplierId index: 'supplier_item_supplier_id_idx'
        itemId index: 'supplier_item_item_id_idx'
        createdBy index: 'supplier_item_created_by_idx'
        updatedBy index: 'supplier_item_updated_by_idx'
    }

    static constraints = {
        itemId(nullable: false)
        supplierId(nullable: false)
        companyId(nullable: false)
        createdBy(nullable: false)
        createdOn(nullable: false)
        updatedBy(nullable: false)
        updatedOn(nullable: true)
    }
}