/**
 * Module Name - Procurement
 * Purpose - Entity of procurement transport cost information
 **/

package com.athena.mis.procurement.entity

class ProcTransportCost {
    long id                   // primary key (Auto generated by its own sequence)
    int version
    long purchaseOrderId      // ProcPurchaseOrder.id (Parent)
    double amount             // Tr. Cost amount(Not quantity*rate)
    double quantity           // Tr.Cost quantity
    double rate               // Tr. Cost rate
    String comments

    static mapping = {
        id generator: 'sequence', params: [sequence: 'proc_transport_cost_id_seq']
        amount sqlType: "numeric(16,4)"
        quantity sqlType: "numeric(16,4)"
        rate sqlType: "numeric(16,4)"

        purchaseOrderId index: 'proc_transport_cost_purchase_order_id_idx'
    }

    static constraints = {
        comments(nullable: true);
    }
}
