package com.athena.mis.sarb.entity

/*
  Additional task details needed for SARB integration
 */

class SarbTaskDetails {

    long id                             // primary key (Auto generated by its own sequence)
    int version                         // version of persisted object
    long taskId                         // exhTask.id
    long submittedFileCount             // File name counter e.g. 1082014000001
    String originalFileName             // submitted file name e.g. 10820140000001.xml
    String originalFileContent          // submitted file's xml content
    String originalResponse             // response after file submission
    boolean isSubmittedToSarb           // flag to check if file has been submitted
    String responseOfRetrieveReference  // sarb response with provides an xml with refNo
    String sarbRefNo					// sarb refNo e.g. SARBREFNEE2077AFEA884519BC45E9FEFEF3D780
	boolean isAcceptedBySarb            // boolean flag if task is accepted By Sarb
    String responseOfReference          // final sarb response containing accept/reject status
    long companyId                      // company.id
    boolean enabled                     // 'true' for new object, if resend to SARB then all previous is 'false'
    boolean isCancelled                 // true if task is cancelled & false if not cancelled
    Date createdOn                      // object creation datetime
    long createdBy                      // appUser.id, who sent to SARB
    long reviseStatus                   // SystemEntity.id


    static constraints = {
        originalFileContent(maxSize: 10000)
        originalResponse(maxSize: 3000)
        responseOfRetrieveReference(nullable: true, maxSize: 1000)
        sarbRefNo(nullable: true)
        responseOfReference(nullable: true, maxSize: 10000)
    }

    static mapping = {
        id generator: 'sequence', params: [sequence: 'sarb_task_details_id_seq']
        taskId index: 'sarb_task_details_task_id_idx'
        companyId index: 'sarb_task_details_company_id_idx'
    }
}
