package com.athena.mis.sarb.entity
/*
    Domain to keep pre-defined provinces provided by SARB
*/

class SarbProvince {

    long id             // primary key (Auto generated by its own sequence)
    int version         // version of persisted object
    String name         // name of province
    long companyId      // company.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'sarb_province_id_seq']
        companyId index: 'sarb_province_company_id_idx'
    }

    static constraints = {
    }

}
