package com.athena.mis.sarb.entity

class SarbCustomerDetailsTrace {

	long id                 // primary key (Auto generated by its own sequence)
	long customerTraceId    // ExhCustomerTrace.id
	long customerId         // exhCustomer.id (redundant)
	String suburb           // suburb name of customer
	String city             // city name of customer
	long provinceId         // province.id
	String contactSurname   // surname of contact person
	String contactName      // name of contact person
	long companyId			//Company.id

	static constraints = {
	}

	static mapping = {
		version false
		id generator: 'sequence', params: [sequence: 'sarb_customer_details_trace_id_seq']
		customerTraceId index: 'sarb_customer_details_trace_customer_trace_id_idx'
	}
}
