/**
 * Module  - Project Track
 * Purpose - Entity that contains all properties of PtSprint
 */

package com.athena.mis.projecttrack.entity

class PtSprint {
    long id             // primary key (Auto generated by its own sequence)
    int version
    String name         // auto generate
    Date startDate      // start date of sprint
    Date endDate        // end date of sprint
    long projectId      // PtProject.id
    long statusId       // SystemEntity.id(dropdown)
    long companyId      // Company.id
    boolean isActive    // boolean value (true/false)

    static mapping = {
        id generator: 'sequence', params: [sequence: 'pt_sprint_id_seq']
        startDate type: 'date'
        endDate type: 'date'

        //indexing
        projectId index: 'pt_sprint_project_id_idx'
        statusId index: 'pt_sprint_status_id_idx'
        companyId index: 'pt_sprint_company_id_idx'
    }

    static constraints = {
        projectId(nullable: false)
        startDate(nullable: false)
        endDate(nullable: false)
        statusId(nullable: false)
    }
}
