/**
 * Module Name - Customer
 * Purpose - Entity of Customer information
 * */

 package com.athena.mis.application.entity

class Customer {
    long id                 // primary key (Auto generated by its own sequence)
    int version
    long companyId          // Company.id
    String fullName         // Full Name of Customer
    String nickName         // Nick Name of Customer
    String phoneNo          // Customer's phone no
    String email            // Customer's email address
    Date dateOfBirth        // Customer's birth date
    String address          // Customer's address
    long createdBy          // AppUser.id
    Date createdOn          // Object creation DateTime
    long updatedBy = 0L     // AppUser.id
    Date updatedOn          // Object Updated DateTime

    static mapping = {
        id generator: 'sequence', params: [sequence: 'customer_id_seq']
        companyId index: 'customer_company_id_idx'
        createdBy index: 'customer_created_by_idx'
        updatedBy index: 'customer_updated_by_idx'
    }

    static constraints = {
        companyId(nullable: false)
        email(nullable: true)
        address(nullable: true)
        phoneNo(nullable: true)
        createdBy(nullable: false)
        createdOn(nullable: false)
        updatedBy(nullable: false)
        updatedOn(nullable: true)
    }

    public String toString() {
        return this.fullName
    }
}
