/**
 * Module  - Inventory
 * Purpose - Entity that contains all properties of Inventory Transaction Details
 */

package com.athena.mis.inventory.entity

class InvInventoryTransactionDetails {
    long id                         // primary key (Auto generated by its own sequence)
    int version                     // Object version in persistence layer
    long inventoryTransactionId     // parent id

    // property transactionDetailsId: e.g. foreign key of site transaction details id for store in from site
    // e.g. purchaseOrderDetails.id
    long transactionDetailsId

    long inventoryTypeId            // e.g. Store, Site
    long inventoryId                // Store ID, Site ID etc.

    long approvedBy                 // AppUser.id

    long itemId                     // Item.id
    long vehicleId                  // Vehicle.id
    String vehicleNumber
    double suppliedQuantity         // Item quantity that send to store from supplier or site
    double actualQuantity           // Item quantity that receive to store
    double shrinkage                // Item quantity difference from actualQuantity to suppliedQuantity
    double rate

    String supplierChalan
    String stackMeasurement
    double fifoQuantity             // optional in storeOut
    double lifoQuantity             // optional in storeOut
    long acknowledgedBy             // foreign key of AppUser (default 0. value entered when Acknowledged from Site In)

    Date createdOn                  // Object creation DateTime
    long createdBy                  // AppUser.id
    Date updatedOn                  // Object updated DateTime
    long updatedBy                  // AppUser.id

    long invoiceAcknowledgedBy      // AppUser.id

    String comments

    //for inventoryOut specific purpose
    String mrfNo                    // Required
    Date transactionDate            // user defined date

    /* If itemId at BudgetDetails is isConsumedAgainstFixedAsset = true,
     then set fixedAssetId && fixedAssetDetailsId
     OtherWise set 0 at both field*/
    long fixedAssetId               //FixedAsset.id
    long fixedAssetDetailsId

    long transactionTypeId
    long adjustmentParentId
    Date approvedOn
    boolean isIncrease
    boolean isCurrent

    /* When Production-With-Consumption then set overheadCost
       Otherwise Set = 0.0
    */
    double overheadCost

    static mapping = {
        id generator: 'sequence', params: [sequence: 'inv_inventory_transaction_details_id_seq']
        suppliedQuantity sqlType: "numeric(16,4)"
        actualQuantity sqlType: "numeric(16,4)"
        shrinkage sqlType: "numeric(16,4)"
        rate sqlType: "numeric(16,4)"
        fifoQuantity sqlType: "numeric(16,4)"
        lifoQuantity sqlType: "numeric(16,4)"
        transactionDate type: 'date'
        overheadCost sqlType: "numeric(16,4)"

        inventoryTransactionId index: 'inv_inventory_transaction_details_inventory_transaction_id_idx'
        transactionDetailsId index: 'inv_inventory_transaction_details_transaction_details_id_idx'
        inventoryTypeId index: 'inv_inventory_transaction_details_inventory_type_id_idx'
        inventoryId index: 'inv_inventory_transaction_details_inventory_id_idx'
        approvedBy index: 'inv_inventory_transaction_details_approved_by_idx'
        approvedOn index: 'inv_inventory_transaction_details_approved_on_idx'
        itemId index: 'inv_inventory_transaction_details_item_id_idx'
        vehicleId index: 'inv_inventory_transaction_details_vehicle_id_idx'
        actualQuantity index: 'inv_inventory_transaction_details_actual_quantity_idx'
        fifoQuantity index: 'inv_inventory_transaction_details_fifo_quantity_idx'
        lifoQuantity index: 'inv_inventory_transaction_details_lifo_quantity_idx'
        rate index: 'inv_inventory_transaction_details_rate_idx'
        transactionDate index: 'inv_inventory_transaction_details_transaction_date_idx'
        createdBy index: 'inv_inventory_transaction_details_created_by_idx'
        updatedBy index: 'inv_inventory_transaction_details_updated_by_idx'
        fixedAssetId index: 'inv_inventory_transaction_details_fixed_asset_id_idx'
        fixedAssetDetailsId index: 'inv_inventory_transaction_details_fixed_asset_details_id_idx'
        transactionTypeId index: 'inv_inventory_transaction_details_transaction_type_id_idx'
        invoiceAcknowledgedBy index: 'inv_inventory_transaction_details_invoice_acknowledged_by_idx'
    }

    static constraints = {
        updatedOn(nullable: true)
        comments(nullable: true)
        vehicleNumber(nullable: true)
        supplierChalan(nullable: true)
        mrfNo(nullable: true)
        stackMeasurement(nullable: true)
        transactionTypeId(nullable: false)
        adjustmentParentId(nullable: false)
        approvedOn(nullable: true)
        isIncrease(nullable: false)
        isCurrent(nullable: false)
        invoiceAcknowledgedBy(nullable: false)
        overheadCost(nullable: false)
    }
}
