package com.athena.mis.accounting.entity

class AccIpc {

    long id                         // primary key (Auto generated by its own sequence)
    int version
    String ipcNo                    // Ipc No
    long projectId                  // Project.id
    long companyId                  // Company.id

    long createdBy                  // AppUser.id
    Date createdOn                  // Object creation DateTime
    long updatedBy                  // AppUser.id
    Date updatedOn                  // Object Updated DateTime

    static mapping = {
        id generator: 'sequence', params: [sequence: 'acc_ipc_id_seq']
        projectId index: 'acc_ipc_project_id_idx'
        createdBy index: 'acc_ipc_created_by_idx'
        updatedBy index: 'acc_ipc_updated_by_idx'
        companyId index: 'acc_ipc_company_by_idx'
    }

    static constraints = {
        ipcNo(nullable: false)
        projectId(nullable: false)
        createdBy(nullable: false)
        createdOn(nullable: false)
        updatedOn(nullable: true)
        updatedBy(nullable: false)
        companyId(nullable: false)
    }
}
