package com.athena.mis.application.entity

class AppShellScript {

    long id         //Primary Key (Auto Generated By it's own sequence)
    int version

    String name     // Name of the Category
    String script

    long companyId            //Company.id

    Date createdOn            //Created Datetime
    long createdBy            //AppUser.id
    Date updatedOn            //Updated datetime
    long updatedBy            //AppUser.id


    static constraints = {
        name(nullable: false)
        script(nullable: false, maxSize: 1500)
        companyId(nullable: false)
        createdOn(nullable: false)
        createdBy(nullable: false)
        updatedOn(nullable: true)
        updatedBy(nullable: false)
    }

    static mapping = {
        id generator: 'sequence', params: [sequence: 'app_shell_script_id_seq']
        companyId index: 'app_shell_script_company_id_idx'
    }
}
