package com.athena.mis.application.entity

/**
 * Created by user on 11/5/14.
 */
class CostingType {
    long id                 // primary key (Auto generated by its own sequence)
    int version
    String name             // CostingType Name
    String description      // CostingType description
    long companyId          // Company.id
    long createdBy          // AppUser.id
    Date createdOn          // Object creation DateTime
    long updatedBy = 0L     // AppUser.id
    Date updatedOn          // Object Updated DateTime

    static mapping = {
        id generator: 'sequence', params: [sequence: 'costing_type_id_seq']
        companyId index: 'costing_type_company_id_idx'
        createdBy index: 'costing_type_created_by_idx'
        updatedBy index: 'costing_type_updated_by_idx'
    }

    static constraints = {
        name(blank: false, nullable: false)
        description(blank: false, nullable: true)
        companyId(nullable: false)
        createdBy(nullable: false)
        createdOn(nullable: false)
        updatedBy(nullable: false)
        updatedOn(nullable: true)
    }
}
