package com.athena.mis.application.entity

class Designation {

    long id                 // primary key (Auto generated by its own sequence)
    int version
    long companyId          // Company.id
    String name
    String shortName        // ShortName or COde of name

    long createdBy          // AppUser.id
    Date createdOn          // Object creation DateTime
    long updatedBy = 0L     // AppUser.id
    Date updatedOn          // Object Updated DateTime

    static mapping = {
        id generator: 'sequence', params: [sequence: 'designation_id_seq']
        createdBy index: 'designation_created_by_idx'
        updatedBy index: 'designation_updated_by_idx'
        companyId index: 'designation_company_id_idx'
    }

    static constraints = {
        companyId(nullable: false)
        name(nullable: false)
        shortName(nullable: false)
        createdBy(nullable: false)
        createdOn(nullable: false)
        updatedBy(nullable: false)
        updatedOn(nullable: true)
    }
}
