/**
 * Module  - Application
 * Purpose - Entity that contains all properties of Employee
 */

package com.athena.mis.application.entity

class Employee {

    long id                 // primary key (Auto generated by its own sequence)
    int version
    long companyId          // Company.id
    String fullName         // Full Name of Employee
    String nickName         // Nick Name of Employee
    String mobileNo         // Employee's phone no
    String email            // Employee's email address
    Date dateOfBirth        // Employee's date of birth
    String address          // Employee's address
    Date dateOfJoin         // Employee's date of Joining
    long createdBy          // AppUser.id
    Date createdOn          // Object creation DateTime
    long updatedBy = 0L     // AppUser.id
    Date updatedOn
    long designationId      // Designation.Id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'employee_id_seq']
        dateOfBirth type: 'date'
        dateOfJoin type: 'date'
        createdBy index: 'employee_created_by_idx'
        updatedBy index: 'employee_updated_by_idx'
        companyId index: 'employee_company_id_idx'
        designationId index: 'employee_designation_id_idx'
    }

    static constraints = {
        mobileNo(nullable: true)
        email(nullable: true)
        updatedOn(nullable: true)
        address(nullable: true)
        companyId(nullable: false)
        designationId(nullable: false)
        dateOfBirth(nullable: true)
    }

    public String toString() {
        return this.fullName
    }
}
