package com.athena.mis.application.entity

//to store different type of content(e.g. doc, txt, exl, scanned document image etc...)
class EntityContent {

    long id                    // primary key (Auto generated by its own sequence)
    int version
    long contentCategoryId     // contentCategory.Id  (Signature, Drawing, Logo, Archived file)
    long contentTypeId         // SystemEntity.id  (Document, Image)
    long entityTypeId          // SystemEntity.id (Project, customers, suppliers, appUsers)
    long entityId              // project.id appUsers.id etc
    byte[] content             // content
    String caption             // about entity content
    String extension           // Extension of the content(e.g : doc, txt, exl, png, jpeg, gif etc)
    String fileName            // file name of the content
    long createdBy             // AppUser.id
    Date createdOn             // Object creation DateTime
    long updatedBy = 0L        // AppUser.id
    Date updatedOn             // Object updated DateTime
    long companyId             // Company.id
    Date expirationDate        // expire date of content

    static constraints = {
        contentCategoryId(nullable: false)
        contentTypeId(nullable: false)
        entityTypeId(nullable: false)
        entityId(nullable: false)
        content(nullable: false)
        caption(nullable: true)
        extension(nullable: false)
        fileName(nullable: true)
        createdBy(nullable: false)
        createdOn(nullable: false)
        updatedBy(nullable: false)
        updatedOn(nullable: true)
        companyId(nullable: false)
        expirationDate(nullable: true)
    }

    static mapping = {
        id generator: 'sequence', params: [sequence: 'entity_content_id_seq']
        expirationDate type: 'date'

        contentCategoryId index: 'entity_content_content_category_id_idx'
        contentTypeId index: 'entity_content_content_type_id_idx'
        entityTypeId index: 'entity_content_entity_type_id_idx'
        entityId index: 'entity_content_entity_id_idx'
        createdBy index: 'entity_content_created_by_idx'
        updatedBy index: 'entity_content_updated_by_idx'
        companyId index: 'entity_content_company_id_idx'
    }
}

