/**
 * Module  - Application
 * Purpose - Entity that contains all properties of Employee
 */

package com.athena.mis.application.entity

class EntityNote {
    long id                     // primary key (Auto generated by its own sequence)
    int version
    long entityTypeId           // SystemEntity.id (Customers, Task)
    long entityId               // customers.id, task.id etc
    String note                 // comment body
    long createdBy              // AppUser.id
    Date createdOn              // Object creation DateTime
    long updatedBy = 0L         // AppUser.id
    Date updatedOn              // Object updated DateTime
    long companyId              // Company.id
    int pluginId                // e.g : 1 for Application, 9 for Exchange House etc

    static constraints = {
        entityTypeId(nullable: false)
        entityId(nullable: false)
        note(nullable: false, blank: false, maxSize: 1000)
        createdBy(nullable: false)
        createdOn(nullable: false)
        updatedOn(nullable: true)
        updatedBy(nullable: false)
        companyId(nullable: false)
        pluginId(nullable: false)
    }

    static mapping = {
        id generator: 'sequence', params: [sequence: 'entity_note_id_seq']

        entityTypeId index: 'entity_note_entity_type_id_idx'
        entityId index: 'entity_note_entity_id_idx'
        pluginId index: 'entity_note_plugin_id_idx'
        createdBy index: 'entity_note_created_by_idx'
        companyId index: 'entity_note_company_id_idx'
        updatedBy index: 'entity_note_updated_by_idx'
    }
}

