/**
 * Module Name - Item
 * Purpose - Entity of item
 * */

package com.athena.mis.application.entity

class Item {
    long id                             // primary key (Auto generated by its own sequence)
    int version
    String name                         // Unique item name
    String code                         // Item Code
    String unit                         // Item Unit
    long itemTypeId                     // ItemType.id
    long categoryId                     // SystemEntity.id
    long valuationTypeId                // SystemEntity.id (e.g : FIFO, LIFO etc)

    /* If Item type is Fixed-Asset and have more than 1 Fixed-Asset-Details
           then isIndividualEntity = TRUE
      ELSE for all Items isIndividualEntity = FALSE
     */
    boolean isIndividualEntity = false
    boolean isFinishedProduct = false   // is the item finished product
    long companyId                      // Company.id
    long createdBy                      // AppUser.id
    Date createdOn                      // Object creation DateTime
    long updatedBy = 0L                 // AppUser.id
    Date updatedOn                      // Object Updated DateTime

    static mapping = {
        id generator: 'sequence', params: [sequence: 'item_id_seq']
        name index: 'item_name_idx'
        itemTypeId index: 'item_item_type_id_idx'
        valuationTypeId index: 'item_valuation_type_id_idx'
        companyId index: 'item_company_id_idx'
        createdBy index: 'item_created_by_idx'
        updatedBy index: 'item_updated_by_idx'
    }

    static constraints = {
        name(nullable: false)
        code(nullable: false)
        unit(nullable: false)
        itemTypeId(nullable: false)
        categoryId(nullable: false)
        valuationTypeId(nullable: false)
        isIndividualEntity(nullable: false)
        isFinishedProduct(nullable: false)
        companyId(nullable: false)
        createdBy(nullable: false)
        createdOn(nullable: false)
        updatedBy(nullable: false)
        updatedOn(nullable: true)
    }

    public String toString() {
        return this.name
    }
}
