package com.athena.mis.application.entity

/**
 * Domain class to create new itemType for a particular itemCategory
 */
class ItemType {
    long id              // primary key (Auto generated by its own sequence)
    int version
    String name          // Company-wise unique name
    long categoryId      // SystemEntity.id

    Date createdOn       // Object creation DateTime
    long createdBy       // AppUser.id
    Date updatedOn       // Object updated DateTime
    long updatedBy       // AppUser.id
    long companyId       // Company.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'item_type_id_seq']

        categoryId index: 'item_type_category_id_idx'
        createdBy index: 'item_type_created_by_idx'
        updatedBy index: 'item_type_updated_by_idx'
        companyId index: 'item_type_company_id_idx'
    }

    static constraints = {
        name(nullable: false)
        categoryId(nullable: false)
        createdOn(nullable: false)
        createdBy(nullable: false)
        updatedOn(nullable: true)
        updatedBy(nullable: false)
        companyId(nullable: false)
    }
}