/**
 * Module Name - Application
 * Purpose - Entity of application role
 * */

package com.athena.mis.application.entity

class Role {
    long id             // primary key (Auto generated by its own sequence)
    int version
    String authority    // Role short name format(ROLE_Role.id_Company.id) e.g ROLE_-1_1, ROLE_5_101
    String name         // Role name
    long companyId      // Company.id
    long roleTypeId     // RoleType.id (For any custom created role, RoleTypeId = 0)

    static mapping = {
        cache true
        id generator: 'sequence', params: [sequence: 'role_id_seq']
        companyId index: 'role_company_id_idx'
        roleTypeId index: 'role_role_type_id_idx'
    }

    static constraints = {
        authority(blank: false, unique: true)
        companyId(nullable: false)
        roleTypeId(nullable: false)
    }

    public String toString() {
        return this.authority;
    }
}
