/**
 * Module Name - Application
 * Purpose - Keep vehicle Information
 * */

package com.athena.mis.application.entity

class Vehicle {
    long id                 // primary key (Auto generated by its own sequence)
    int version
    String name             // Vehicle Name
    String description      // Vehicle description
    long companyId          // Company.id
    long createdBy          // AppUser.id
    Date createdOn          // Object creation DateTime
    long updatedBy = 0L     // AppUser.id
    Date updatedOn          // Object Updated DateTime

    static mapping = {
        id generator: 'sequence', params: [sequence: 'vehicle_id_seq']
        companyId index: 'vehicle_company_id_idx'
        createdBy index: 'vehicle_created_by_idx'
        updatedBy index: 'vehicle_updated_by_idx'
    }

    static constraints = {
        name(blank: false, nullable: false)
        description(blank: false, nullable: true)
        companyId(nullable: false)
        createdBy(nullable: false)
        createdOn(nullable: false)
        updatedBy(nullable: false)
        updatedOn(nullable: true)
    }
}