package com.athena.mis.arms.entity

/**
 * Module  - ARMS
 * Purpose - Entity that contains all properties of RmsExchangeHouseCurrencyPosting
 */
class RmsExchangeHouseCurrencyPosting {

    long id                     // primary key (Auto generated by its own sequence)
    int version                 // object version persisted in DB

    long exchangeHouseId        // RmsExchangeHouse.id
    long taskId                 // RmsTask.id
    double amount               // amount of Currency Posting

    long companyId              // Company.id

    long createdBy              // AppUser.id
    Date createdOn              // Object creation DateTime
    long updatedBy = 0L         // AppUser.id
    Date updatedOn

    static mapping = {
        id generator: 'sequence', params: [sequence: 'rms_exchange_house_currency_posting_id_seq']
        amount sqlType: 'numeric(16,2)'
        exchangeHouseId index: 'rms_exchange_house_currency_posting_exchange_house_id_idx'
        taskId index: 'rms_exchange_house_currency_posting_task_id_idx'
        companyId index: 'rms_exchange_house_currency_posting_company_id_idx'
        createdBy index: 'rms_exchange_house_currency_posting_created_id_idx'
        updatedBy index: 'rms_exchange_house_currency_posting_updated_id_idx'
    }

    static constraints = {
        updatedOn(nullable: true)
    }
}
