package com.athena.mis.sarb.entity
/*
  * Additional customer details needed for SARB integration
 */

class SarbCustomerDetails {

    long id                 // primary key (Auto generated by its own sequence)
    int version             // version of persisted object
    long customerId         // exhCustomer.id
    String suburb           // suburb name of customer
    String city             // city name of customer
    long provinceId         // province.id
    String contactSurname   // surname of contact person
    String contactName      // name of contact person
    long companyId          // company.id
    long updatedBy          // AppUser.id
    Date updatedOn          // Object updated DateTime

    static constraints = {
        updatedOn(nullable: true)
    }

    static mapping = {
        id generator: 'sequence', params: [sequence: 'sarb_customer_details_id_seq']
        customerId index: 'sarb_customer_details_customer_id_idx'
        companyId index: 'sarb_customer_details_company_id_idx'
        provinceId index: 'sarb_customer_details_province_id_idx'
    }
}
