/**
 * Module  - ProjectTrack
 * Purpose - Entity that contains all properties of AcceptanceCriteria
 */

package com.athena.mis.projecttrack.entity

class PtAcceptanceCriteria {
	long id          	// object.id (primary key - auto generated by own id_seq)
	int version         // object.version
	String criteria     // criteria
	long statusId       // SystemEntity.id
    long type           // SystemEntity.id
	Date completedOn    // date completed on (type: dateTime)
	long backlogId      // PtBacklog.id
	long companyId      // Company.id

    long createdBy       // AppUser.id
    Date createdOn       // Object creation DateTime

	static constraints = {
		completedOn(nullable: true)
        createdBy(nullable: false)
        createdOn(nullable: false)
	}

	static mapping = {
		id generator: 'sequence' , params: [sequence : 'pt_acceptance_criteria_id_seq']  // id sequence generator of pt_acceptance_criteria domain
        type index: 'pt_acceptance_criteria_type_idx'
        createdBy index: 'pt_acceptance_criteria_created_by_idx'
        statusId index: 'pt_acceptance_criteria_status_id_idx'
		backlogId index: 'pt_acceptance_criteria_backlog_id_idx'
		companyId index: 'pt_acceptance_criteria_company_id_idx'
	}
}
