package com.athena.mis.document.entity

class DocArticle {

    long id                     //Primary Key (Auto Generated By it's own sequence)
    int version
    String title                //Title of the Article
    String details              //Details of the Article
    long categoryId             //DocCategory.id
    long subCategoryId          //DocSubCategory.id
    boolean isMovedToTrash      //Moved to trash true/false for Article
    long companyId              //Company.id
    Date createdOn              //Created Datetime
    long createdBy              //AppUser.id
    Date updatedOn              //Updated datetime
    long updatedBy              //AppUser.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'doc_article_id_seq']
        companyId index: 'doc_article_company_id_idx'
        categoryId index: 'doc_article_category_id_idx'
        subCategoryId index: 'doc_article_sub_category_id_idx'
        createdBy index: 'doc_article_created_by_idx'
        updatedBy index: 'doc_article_updated_by_idx'
    }
    static constraints = {
        title(nullable: false)
        details(nullable: false, maxSize: 15000)
        categoryId(nullable: false)
        subCategoryId(nullable: false)
        isMovedToTrash(nullable: true)
        companyId(nullable: false)
        createdOn(nullable: false)
        createdBy(nullable: false)
        updatedOn(nullable: true)
        updatedBy(nullable: false)
    }
}
