/**
 * Module Name - Accounting
 * Purpose - Entity of accounting Type name
 **/

package com.athena.mis.accounting.entity

class AccType {
    long id                     // primary key (Auto generated by its own sequence)
    int version
    String name                 // Unique name
    String description          // Acc type description
    int orderId                 // use to maintain hierarchy sequence
    String prefix               // prefix accounting type name
    String systemAccountType    // Account type (Asset, Liabilities, Income, Expense)
    long companyId              //Company.id
    int coaCount                //counter for Chart of account(COA) generation in COA CRUD


    static mapping = {
        id generator: 'sequence', params: [sequence: 'acc_type_id_seq']
        companyId index: 'acc_type_company_id_idx'
    }

    static constraints = {
        name(nullable: false)
        description(nullable: true)
        orderId(nullable: false)
        prefix(nullable: false)
        companyId(nullable: false)
        systemAccountType(nullable: false)
        coaCount(nullable: false)
    }

    public String toString() {
        return this.name
    }
}
