/**
 * Module Name - Application
 * Purpose - Entity of company name
 * */

package com.athena.mis.application.entity

class Company {
    long id              // primary key (Auto generated by its own sequence)
    int version
    String name         // Unique Company Name
    long createdBy       // AppUser.id
    Date createdOn       // Object creation DateTime
    long updatedBy = 0L  // AppUser.id
    Date updatedOn       // Object updated DateTime
    String address1       // Company Address
    String address2       // Company Address
    String webUrl         // url of company
    String code          // Company code
    long countryId       // Country.id
    long currencyId      // Currency.id
    String email

    static mapping = {
        id generator: 'assigned'
        countryId index: 'company_country_id_idx'
        createdBy index: 'company_created_by_idx'
        updatedBy index: 'company_updated_by_idx'
        currencyId index: 'company_currency_id_idx'
    }

    static constraints = {
        name(nullable: false)
        address1(nullable: false)
        address2(nullable: true)
        updatedOn(nullable: true)
        code(nullable: false)
        countryId(nullable: false)
        currencyId(nullable: false)
        webUrl(nullable: false)
        email(nullable: true)
        webUrl(unique: true)
        email(unique: true)
    }
}
