/**
 * Module Name - Procurement
 * Purpose - Entity of procurement Terms and Condition information
 **/

package com.athena.mis.procurement.entity

class ProcTermsAndCondition {

    long id                     // primary key (Auto generated by its own sequence)
    int version
    long companyId              //Company.id
    long projectId              // foreign key of project
    long purchaseOrderId        // foreign key of purchaseOrder
    String details

    Date createdOn
    long createdBy          // foreign key of AppUser
    Date updatedOn
    long updatedBy = 0      // foreign key of AppUser

    static mapping = {
        id generator: 'sequence', params: [sequence: 'proc_terms_and_condition_id_seq']

        purchaseOrderId index: 'proc_terms_and_condition_purchase_order_id_idx'

        companyId index: 'proc_terms_and_condition_company_id_idx'
        projectId index: 'proc_terms_and_condition_project_id_idx'
        createdBy index: 'proc_terms_and_condition_created_by_idx'
        updatedBy index: 'proc_terms_and_condition_updated_by_idx'
    }

    static constraints = {
        updatedOn(nullable: true)
        details(size: 1..255)
    }
}
