package com.athena.mis.document.entity

class DocArticleQuery {

    long id                     //Primary Key (Auto Generated By it's own sequence)
    int version
    String name                 //Name of the Article Query
    long contentTypeId          //Content Type of the Article Query(SystemEntity.id)
    String criteria             //Criteria for Article Query
    long companyId              //Company.id
    Date createdOn              //Created Datetime
    long createdBy              //AppUser.id
    Date updatedOn              //Updated datetime
    long updatedBy              //AppUser.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'doc_article_query_id_seq']
        companyId index: 'doc_article_query_company_id_idx'
        contentTypeId index: 'doc_article_query_content_type_id_idx'
        createdBy index: 'doc_article_query_created_by_idx'
        updatedBy index: 'doc_article_query_updated_by_idx'
    }
    static constraints = {
        name(nullable: false)
        contentTypeId(nullable: false)
        criteria(nullable: false)
        companyId(nullable: false)
        createdOn(nullable: false)
        createdBy(nullable: false)
        updatedOn(nullable: true)
        updatedBy(nullable: false)
    }
}
