package com.athena.mis.document.entity

class DocInvitedMembersCategory {

    long id                         //Primary Key (Auto Generated By it's own sequence)
    long invitedMemberId            // DocInvitedMembers.id
    long categoryId                 // DocCategory.id
    long subCategoryId              // DocSubCategory.id

    static mapping = {
        version false
        id generator: 'sequence', params: [sequence: 'doc_invited_members_category_id_seq']
        invitedMemberId index: 'doc_invited_members_category_invited_member_id_idx'
        categoryId index: 'doc_invited_members_category_category_id_idx'
        subCategoryId index: 'doc_invited_members_category_sub_category_id_idx'
    }
    static constraints = {
        invitedMemberId(nullable: false)
        categoryId(nullable: false)
        subCategoryId(nullable: false)

    }
}
