/**
 * Module Name - Fixed asset
 * Purpose - Entity of Fixed asset Category Maintenance Type information
 * */

 package com.athena.mis.fixedasset.entity

class FxdCategoryMaintenanceType {

    long id                 // primary key (Auto generated by its own sequence)
    int version
    long itemId             // Item.id
    long maintenanceTypeId  // MaintenanceType.id

    Date createdOn          // Object creation DateTime
    long createdBy          // AppUser.id
    Date updatedOn          // Object updated DateTime
    long updatedBy          // AppUser.id

    long companyId          // Company.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'fxd_category_maintenance_type_id_seq']

        itemId index: 'fxd_category_maintenance_type_item_id_idx'
        maintenanceTypeId index: 'fxd_category_maintenance_type_maintenance_type_id_idx'
        createdBy index: 'fxd_category_maintenance_type_created_by_idx'
        updatedBy index: 'fxd_category_maintenance_type_updated_by_idx'
        companyId index: 'fxd_category_maintenance_type_company_id_idx'
    }

    static constraints = {
        itemId(nullable: false)
        maintenanceTypeId(nullable: false)
        createdOn(nullable: false)
        createdBy(nullable: false)
        updatedOn(nullable: true)
        updatedBy(nullable: false)
        companyId(nullable: false)
    }
}
