/**
 * Module Name - Fixed asset
 * Purpose - Entity of Fixed asset details information
 * */

 package com.athena.mis.fixedasset.entity

class FxdFixedAssetDetails {

    long id                 // primary key (Auto generated by its own sequence)
    int version
    long itemId             // Item.id
    double cost             // cost of item taken from its Purchase Order
    String name             // Model or Serial No. of the item
    String description
    long currentInventoryId // current inventory of the item
    long poId
    long supplierId         // supplierId of PO
    long projectId          // projectId of PO
    Date purchaseDate       //Purchase date of item

    Date createdOn          // Object creation DateTime
    long createdBy          // AppUser.id
    Date updatedOn          // Object Updated DateTime
    long updatedBy          // AppUser.id
    long ownerTypeId        // SystemEntity.id (e.g: Rental or Purchase)
    Date expireDate         //if rental then set Expire date

    long companyId          // Company.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'fxd_fixed_asset_details_id_seq']
        purchaseDate type: 'date'
        expireDate type: 'date'

        itemId index: 'fixed_asset_details_item_id_idx'
        currentInventoryId index: 'fixed_asset_details_current_inventory_id_idx'
        supplierId index: 'fixed_asset_details_supplier_id_idx'
        poId index: 'fixed_asset_details_po_id_idx'
        projectId index: 'fixed_asset_details_project_id_idx'
        purchaseDate index: 'fixed_asset_details_purchase_date_idx'
        createdBy index: 'fixed_asset_details_created_by_idx'
        updatedBy index: 'fixed_asset_details_updated_by_idx'
        ownerTypeId index: 'fixed_asset_details_owner_type_id_idx'
        companyId index: 'fixed_asset_details_company_id_idx'
    }

    static constraints = {
        itemId(nullable: false)
        cost(nullable: false)
        name(nullable: false)
        description(nullable: true)
        currentInventoryId(nullable: false)
        poId(nullable: false)
        supplierId(nullable: false)
        purchaseDate(nullable: false)
        createdOn(nullable: false)
        createdBy(nullable: false)
        updatedOn(nullable: true)
        updatedBy(nullable: false)
        ownerTypeId(nullable: false)
        expireDate(nullable: true)
        companyId(nullable: false)
    }
}
