/**
 * Module Name - Procurement
 * Purpose - Entity of Indent
 * */
package com.athena.mis.procurement.entity

class ProcIndent {
    long id                                 // primary key (Auto generated by its own sequence)
    int version
    long projectId                          // Project.id
    int itemCount = 0                      // no of item for this PR
    double totalPrice                       // sum of indent item

    String comments
    Date fromDate                           // from date to consume ProcIndent materials
    Date toDate                             // to date to consume ProcIndent materials

    Date createdOn                          // Object Creation DateTime
    long createdBy                          // AppUser.id

    Date updatedOn                          // Object updated DateTime
    long updatedBy                          // AppUser.id

    long approvedBy                          // AppUser.id
    long companyId                           // Company.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'proc_indent_id_seq']
        fromDate type: 'date'
        toDate type: 'date'
        totalPrice sqlType: "numeric(16,4)"

        projectId index: 'proc_indent_project_id_idx'
        createdBy index: 'proc_indent_created_by_idx'
        updatedBy index: 'proc_indent_updated_by_idx'
        approvedBy index: 'proc_indent_approved_by_idx'
        companyId index: 'proc_indent_company_id_idx'

    }

    static constraints = {
        comments(nullable: true)
        updatedOn(nullable: true)
        approvedBy(nullable: false)
    }
}
