package com.athena.mis.accounting.entity

class AccLeaseAccount {

    long id                          // primary key (Auto generated by its own sequence)
    int version
    String institution               // name of the institution
    long itemId                      // Item.id
    double amount                    // Lease amount
    Date startDate                   // Lease start on
    Date endDate                     // Lease ends on
    double interestRate              // interest rate
    int noOfInstallment              // total installment number
    double installmentVolume        // total size of installment

    long companyId                  // Company.id

    long createdBy                  // AppUser.id
    Date createdOn                  // Object creation DateTime
    long updatedBy                  // AppUser.id
    Date updatedOn                  // Object Updated DateTime

    static mapping = {
        startDate type: 'date'
        endDate type: 'date'
        id generator: 'sequence', params: [sequence: 'acc_lease_account_id_seq']
        itemId index: 'acc_lease_account_item_idx'
        createdBy index: 'acc_lease_account_created_by_idx'
        updatedBy index: 'acc_lease_account_updated_by_idx'
        companyId index: 'acc_lease_account_company_by_idx'
    }

    static constraints = {
        institution(nullable: false)
        itemId(nullable: false)
        amount(nullable: false)
        interestRate(nullable: false)
        noOfInstallment(nullable: false)
        installmentVolume(nullable: false)
        startDate(nullable: false)
        endDate(nullable: false)
        createdBy(nullable: false)
        createdOn(nullable: false)
        updatedOn(nullable: true)
        updatedBy(nullable: false)
        companyId(nullable: false)
    }
}
