/**
 * Module  - Inventory
 * Purpose - Entity that contains all properties of Production Line Item
 */

package com.athena.mis.inventory.entity

class InvProductionLineItem {

    long id               // primary key (Auto generated by its own sequence)
    int version           // Object version in persistence layer
    String name           // name of production line item (e.g: create ReadyMix, create stone chips)
    long companyId        // Company.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'inv_production_line_item_id_seq']
        companyId index: 'inv_production_line_item_company_id_idx'

    }

    static constraints = {
        name(nullable: false)
        companyId(nullable: false)
    }
}
