/**
 * Module Name - Budget
 * Purpose - Entity of budget and budget scope mapping
 **/

package com.athena.mis.budget.entity

class BudgProjectBudgetScope {
    long id                  // primary key (Auto generated by its own sequence)
    int version
    long projectId           // Project.id
    long budgetScopeId       // BudgBudgetScope.id
    long companyId

    static mapping = {
        id generator: 'sequence', params: [sequence: 'budg_project_budget_scope_id_seq']
        version false
        projectId index: 'budg_project_budget_scope_project_id_idx'
        budgetScopeId index: 'budg_project_budget_scope_budget_scope_id_idx'
    }
    static constraints = {
    }
}
