package com.athena.mis.document.entity

class DocSubCategoryUserMapping {

    long id                         //Primary Key (Auto Generated By it's own sequence)
    int version
    long userId                     //AppUser.id
    boolean isSubCategoryManager    //true/false sub category manager
    boolean isFavourite

    long categoryId                 //DocCategory.id
    long subCategoryId              //DocSubCategory.id

    long companyId                  //Company.id

    long createdBy                  //AppUser.id
    Date createdOn                  //Created Datetime
    long updatedBy                  //AppUser.id
    Date updatedOn                  //updated Datetime

    static mapping = {
        id generator: 'sequence', params: [sequence: 'doc_sub_category_user_mapping_id_seq']
        userId index: 'doc_sub_category_user_mapping_user_id_idx'
        categoryId index: 'doc_sub_category_user_mapping_category_id_idx'
        subCategoryId index: 'doc_sub_category_user_mapping_sub_category_id_idx'
        companyId index: 'doc_sub_category_user_mapping_company_id_idx'
        createdBy index: 'doc_sub_category_user_mapping_created_by_idx'
        updatedBy index: 'doc_sub_category_user_mapping_updated_by_idx'
    }

    static constraints = {
        userId(nullable: false)
        categoryId(nullable: false)
        subCategoryId(nullable: false)
        isSubCategoryManager(nullable: false)
        isFavourite(nullable: false)
        companyId(nullable: false)
        createdBy(nullable: false)
        createdOn(nullable: false)
        updatedBy(nullable: false)
        updatedOn(nullable: true)
    }
}
