/**
 * Module Name - Procurement
 * Purpose - Entity of  indent details
 * */

package com.athena.mis.procurement.entity

import com.athena.mis.utility.Tools

class ProcIndentDetails {

    long id                 // primary key (Auto generated by its own sequence)
    int version
    long indentId           // Indent.Id (parent)
    long projectId          // Project.id (Redundant)
    String itemDescription
    String unit
    double quantity
    double rate
    String comments

    Date createdOn         // Object Creation DateTime
    long createdBy          // AppUser.id
    Date updatedOn         // Object Updated DateTime
    long updatedBy = 0      // AppUser.id
    long companyId         // Company.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'proc_indent_details_id_seq']
        quantity sqlType: "numeric(16,4)"
        rate sqlType: "numeric(16,4)"

        indentId index: 'proc_indent_details_indent_id_idx'
        projectId index: 'proc_indent_details_project_id_idx'
        createdBy index: 'proc_indent_details_created_by_idx'
        updatedBy index: 'proc_indent_details_updated_by_idx'
        companyId index: 'proc_indent_details_company_id_idx'
    }

    static constraints = {
        comments(nullable: true)
        updatedOn(nullable: true)
        rate(nullable: false)
        itemDescription(nullable: false, size: 0..1000)
    }

    static namedQueries = {

        searchByIndentId { long indentId, String queryType, String queryName ->
            eq('indentId', indentId)
            ilike(queryType, Tools.PERCENTAGE + queryName + Tools.PERCENTAGE)
            setReadOnly(true)
        }
    }
}
