/**
 * Module Name - AccIouPurpose
 * Purpose - Create Purpose of IOU Slip
 **/

package com.athena.mis.accounting.entity

class AccIouPurpose {

    long id                         // primary key (Auto generated by its own sequence)
    int version
    long accIouSlipId               // AccIouSlip.id
    long indentDetailsId            // IndentDetails.id
    String comments                 // field for comments
    double amount

    long createdBy                  // foreign key of AppUser
    Date createdOn                  // Object creation DateTime
    long updatedBy                  // AppUser.id
    Date updatedOn                  // Object Updated DateTime

    static mapping = {
        id generator: 'sequence', params: [sequence: 'acc_iou_purpose_id_seq']
        accIouSlipId index: 'acc_iou_purpose_acc_iou_slip_id_idx'
        indentDetailsId index: 'acc_iou_purpose_acc_indent_details_id_idx'
        createdBy index: 'acc_iou_purpose_created_by_idx'
        updatedBy index: 'acc_iou_purpose_updated_by_idx'
    }

    static constraints = {
        accIouSlipId(nullable: false)
        indentDetailsId(nullable: false)
        comments(nullable: true)
        createdBy(nullable: false)
        createdOn(nullable: false)
        updatedBy(nullable: false)
        updatedOn(nullable: true)
        amount sqlType: "numeric(16,4)"
    }
}
