/**
 * Module  - Inventory
 * Purpose - Entity that contains all properties of Inventory
 */

package com.athena.mis.inventory.entity

class InvInventory  {

    long id                     // primary key (Auto generated by its own sequence)
    int version                 // Object version in persistence layer
    long projectId              // Project.id
    String name                 // name of inventory
    String description          // description of inventory
    boolean isFactory = false   // is this inventory Factory or not
    long typeId                 // SystemEntity.id (e.g: Store, Site)
    long companyId              // Company.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'inv_inventory_id_seq']

        name index: 'inv_inventory_name_idx'
        projectId index: 'inv_inventory_project_id_idx'
        typeId index: 'inv_inventory_type_id_idx'
        companyId index: 'inv_inventory_company_id_idx'
    }

    static constraints = {
        name(nullable: false)
        projectId(nullable: false)
        description(nullable: true)
        isFactory (nullable: false)
        typeId (nullable: false)
        companyId (nullable: false)
    }
}
