package com.athena.mis.arms.entity

/**
 * Module  - ARMS
 * Purpose - Entity that contains all properties of RmsProcessInstrumentMappingService
 */
class RmsProcessInstrumentMapping {

    long id                     // primary key (Auto generated by its own sequence)
    int version                 // object version persisted in DB

    long processType            // SystemEntity.id
    long instrumentType         // SystemEntity.id

    long companyId              // Company.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'rms_process_instrument_mapping_id_seq']
        processType index: 'rms_process_instrument_mapping_process_type_idx'
        instrumentType index: 'rms_process_instrument_mapping_instrument_type_idx'
        companyId index: 'rms_process_instrument_mapping_company_id_idx'
    }

    static constraints = {
    }
}
