package com.athena.mis.arms.entity

import com.athena.mis.utility.Tools

/**
 * Module  - ARMS
 * Purpose - Entity that contains all properties of RmsTask
 */
class RmsTask {

    long id                             // primary key (Auto generated by its own sequence)
    int version                         // object version persisted in DB

    String refNo                        // Reference number of task
    double amount                       // amount of task
    Date valueDate                      //
    String beneficiaryName              // Beneficiary name of task
    String beneficiaryAddress           // Beneficiary address of task
    String beneficiaryPhone             // Beneficiary phone of task
    String accountNo                    //
    String outletBank                   //
    String outletBranch                 //
    String outletDistrict               //
    String pinNo                        //
    String identityType                 //
    String identityNo                   //
    String senderName                   //
    String senderMobile                 //
    double amountInLocalCurrency        //
    long localCurrencyId = 0L           // Currency.id
    long paymentMethod                  // SystemEntity.id (Payment method)
    boolean isRevised                   //
    String revisionNote                 //
    long previousStatus                 // SystemEntity.id (Task status)
    long currentStatus                  // SystemEntity.id (Task status)
    Date createdOn                      // Object creation DateTime
    long exchangeHouseId                // RmsExchangeHouse.id
    long currencyId                     // Currency.id
    long countryId                      // Country.id
    long companyId                      // Company.id
    long mappingBankId                  // Bank.id
    long mappingBranchId                // Branch.id
    long mappingDistrictId              // District.id
    long processTypeId                  // SystemEntity.id (Process Type)
    long instrumentTypeId               // SystemEntity.id (Instrument Type)
    Date mappedOn                       //
    Date approvedOn                     // Task approved DateTime
    long taskListId                     // TaskList.id
    long commissionDetailsId            // RmsCommissionDetails.id

    static mapping = {
        id generator: 'sequence', params: [sequence: 'rms_task_id_seq']
        valueDate type: 'date'
        localCurrencyId index: 'rms_task_local_currency_id_idx'
        paymentMethod index: 'rms_task_payment_method_idx'
        previousStatus index: 'rms_task_previous_status_idx'
        currentStatus index: 'rms_task_current_status_idx'
        exchangeHouseId index: 'rms_task_exchange_house_id_idx'
        currencyId index: 'rms_task_currency_id_idx'
        countryId index: 'rms_task_country_id_idx'
        mappingBankId index: 'rms_task_mapping_bank_id_idx'
        mappingBranchId index: 'rms_task_mapping_branch_id_idx'
        mappingDistrictId index: 'rms_task_mapping_district_id_idx'
        processTypeId index: 'rms_task_process_type_id_idx'
        instrumentTypeId index: 'rms_task_instrument_type_id_idx'
        taskListId index: 'rms_task_task_list_id_idx'
        refNo index: 'rms_task_ref_no_idx'
        createdOn index: 'rms_task_created_on_idx'
        commissionDetailsId index: 'rms_task_commission_details_id_idx'
    }

    static constraints = {
        beneficiaryAddress(nullable: true)
        beneficiaryPhone(nullable: true)
        accountNo(nullable: true)
        pinNo(nullable: true)
        identityType(nullable: true)
        identityNo(nullable: true)
        senderName(nullable: true)
        senderMobile(nullable: true)
        revisionNote(nullable: true)
        mappedOn(nullable: true)
        approvedOn(nullable: true)
        refNo unique: 'companyId'
        pinNo unique: 'exchangeHouseId'
    }

    public String getFullOutletName() {
        return this.outletBank + Tools.COMA + Tools.SINGLE_SPACE + this.outletBranch + Tools.COMA + Tools.SINGLE_SPACE + this.outletDistrict
    }
}
